variables:
  FF_NETWORK_PER_BUILD: "true"
  BASE_IMAGE: ubuntu

.versions:
  v2204: &v2204
    UBUNTU_VERSION: "22.04@sha256:3b06811b2afd352be909dd088a004166d665dc76d38b13eada33522a9d915c6f"
    DOCKER_VERSION: "24.0.9"
  v2404: &v2404
    UBUNTU_VERSION: "24.04@sha256:561618e2c15bf2397621dd04f96926663a3b5616c189cf7e38db7e82f5c538ea"
    DOCKER_VERSION: "27.5.1"

build:
  image: docker:latest@sha256:e8faad5a8dc5279dff929afc5449f2791736912fff9f99351d742db2fad01b4c
  tags:
    - $RUNNER_TAG

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG_SUFFIX: "-mr${CI_MERGE_REQUEST_IID}"
    # No suffix for default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        TAG_SUFFIX: ""

  script:
    - apk add bash
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
      docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}";
      fi
    - ./bin/build.sh

  parallel:
    matrix:
      - <<: *v2204
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *v2204
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *v2404
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *v2404
        ARCH: arm64
        RUNNER_TAG: thelab-arm64

manifest:
  needs:
    - build
  image: docker:latest@sha256:e8faad5a8dc5279dff929afc5449f2791736912fff9f99351d742db2fad01b4c
  tags:
    - thelab-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"

  script:
    - apk add bash
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_TOKEN}"
    - ./bin/push-manifest.sh

  parallel:
    matrix:
      - <<: *v2204
      - <<: *v2404
        IS_LATEST: "true"
