variables:
  FF_NETWORK_PER_BUILD: "true"
  BASE_IMAGE: ubuntu

.versions:
  v2204: &v2204
    UBUNTU_VERSION: "22.04@sha256:2edbbc5dc405e9612ba3584ce95480277e3eb374407b5505fe26f17df77c7dbc"
    DOCKER_VERSION: "24.0.9"
  v2404: &v2404
    UBUNTU_VERSION: "24.04@sha256:d78ab76437b1afc5f01e223d6bf0172763f404bb166441328845adbef44518cb"
    DOCKER_VERSION: "27.5.1"

build:
  image: docker:latest@sha256:12e683a161823b2a839aeea999b9d960e6e1f9a97b1679ad6b441982e2d9cf07
  tags:
    - $RUNNER_TAG

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG_SUFFIX: "-mr${CI_MERGE_REQUEST_IID}"
    # No suffix for default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        TAG_SUFFIX: ""

  script:
    - apk add bash
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
      docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}";
      fi
    - ./bin/build.sh

  parallel:
    matrix:
      - <<: *v2204
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *v2204
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *v2404
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *v2404
        ARCH: arm64
        RUNNER_TAG: thelab-arm64

manifest:
  needs:
    - build
  image: docker:latest@sha256:12e683a161823b2a839aeea999b9d960e6e1f9a97b1679ad6b441982e2d9cf07
  tags:
    - thelab-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"

  script:
    - apk add bash
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_TOKEN}"
    - ./bin/push-manifest.sh

  parallel:
    matrix:
      - <<: *v2204
      - <<: *v2404
        IS_LATEST: "true"
