variables:
  FF_NETWORK_PER_BUILD: "true"
  BASE_IMAGE: ubuntu

.versions:
  v2204: &v2204
    UBUNTU_VERSION: "22.04@sha256:445586e41c1de7dfda82d2637f5ff688deea9eb5f5812f8c145afacc35b9f0db"
    DOCKER_VERSION: "24.0.9"
  v2404: &v2404
    UBUNTU_VERSION: "24.04@sha256:0d39fcc8335d6d74d5502f6df2d30119ff4790ebbb60b364818d5112d9e3e932"
    DOCKER_VERSION: "27.5.1"

build:
  image: docker:latest@sha256:1ba18449911d01f477a3fc104123c85d677addc60701b14b3fcb5381f9c4a537
  tags:
    - $RUNNER_TAG

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG_SUFFIX: "-mr${CI_MERGE_REQUEST_IID}"
    # No suffix for default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        TAG_SUFFIX: ""

  script:
    - apk add bash
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
      docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}";
      fi
    - ./bin/build.sh

  parallel:
    matrix:
      - <<: *v2204
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *v2204
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *v2404
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *v2404
        ARCH: arm64
        RUNNER_TAG: thelab-arm64

manifest:
  needs:
    - build
  image: docker:latest@sha256:1ba18449911d01f477a3fc104123c85d677addc60701b14b3fcb5381f9c4a537
  tags:
    - thelab-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"

  script:
    - apk add bash
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_TOKEN}"
    - ./bin/push-manifest.sh

  parallel:
    matrix:
      - <<: *v2204
      - <<: *v2404
        IS_LATEST: "true"
